In [ ]:
#Practice Exercise:
#Store the marks and IDs of three students as NumPy arrays. The marks are [20, 30, 40] and IDs are [0,2,4]. Store array for marks in a variable marks and the one for IDs in another variable ids. Display both marks and ids.

#Given two NumPy arrays arr1 = [25, 56, 12, 85, 34, 75] and arr2 = [42, 3, 86, 32, 856, 46], solve the following:

#a. Create a new NumPy array Narr with the shape equal to arr1 filled with random values.

#b. Permanently change the dtype of arr1 to complex

#Hint: Use np.random.rand() Use astype().

#Answer: [ 25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]

In [ ]:
#Store array for marks in a variable marks and  IDs in variable ids. Display both marks and ids.
import numpy as np
import random

l1=[20,30,40]
l2=[0,2,4]
marks=np.array(l1)
Ids=np.array(l2)
print(marks)
print(Ids)


[20 30 40]
[0 2 4]


In [ ]:
# Create a new NumPy array Narr with the shape equal to arr1 filled with random values.
arr1 = [25, 56, 12, 85, 34, 75]
arr2 = [42, 3, 86, 32, 856, 46]
Narr1=np.array(arr1)
Narr2=np.array(arr2)
np.random.rand()
narr=np.random.randint(100, size=(6))
print(narr)

[33 62 82  3 32 86]


In [ ]:
#Permanently change the dtype of arr1 to complex
array1=Narr1.astype(dtype=complex)
print(array1)


[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]
