**Mini Project 2**
Let us build a complete project using NumPy (without any help).

Path: project_data = 'KAG_Conversion_Data.csv'
**Features:**
* 1.ad_id: unique ID for each ad.
* 2.xyzcampaignid: an ID associated with each ad campaign of XYZ company
* 3.fbcampaignid: an ID associated with how Facebook tracks each campaign
* 4.age: age of the person to whom the ad is shown
* 5.gender: gender of the person to whom the add is shown
* 6.interest: a code specifying the category to which the person’s interest  
  belongs (interests are as mentioned in the person’s Facebook public profile)
* 7.Impressions: the number of times the ad was shown
* 8.Clicks: number of clicks on for that ad
* 9 Spent: Amount paid by company xyz to Facebook, to show that ad
* 10 Total conversion: Total number of people who enquired about the product   
   after seeing the ad
* 11 Approved conversion: Total number of people who bought the product after  
   seeing the ad.

**Instructions:**
* Load the data. Data is already given to you in variable path

* How many unique ad campaigns (xyzcampaignid) does this data contain ? And for 
  how many times was each campaign run ?

* What are the age groups that were targeted through these ad campaigns?

* What was the average, minimum and maximum amount spent on the ads?

* What is the id of the ad having the maximum number of clicks ?

* How many people bought the product after seeing the ad with most clicks? Is  
   that the maximum number of purchases in this dataset?

* So the ad with the most clicks didn't fetch the maximum number of purchases. 
  Find the details of the product having maximum number of purchases.

In [1]:
# Import the Numpy Library & read the data file
import numpy as np
data_file='/content/KAG_Conversion_Data.csv'

In [2]:
#load the data

data=np.genfromtxt(data_file,delimiter=',',skip_header=1)

In [3]:
#print the data & type of data
print(data)
print(type(data))

[[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]
<class 'numpy.ndarray'>


 **ad_id: unique ID for each ad**

In [4]:
ad_id=np.unique(data[:,0]) 
ad_id
#len(ad_id)

array([ 708746.,  708749.,  708771., ..., 1314412., 1314414., 1314415.])

**xyzcampaignid: an ID associated with each ad campaign of XYZ company**.

In [5]:
xyzcampaignid=np.unique(data[:,1])
xyzcampaignid

array([ 916.,  936., 1178.])

**How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?**

In [6]:
unique_ad_campaigns=len(data[:,1])

print("The data contain unique ad campaign is " ,unique_ad_campaigns)


The data contain unique ad campaign is  1143


In [7]:
l=list(data[:,1])
print(l.count(916),"many times 916 run")
print(l.count(936),"many times 936 run")
print(l.count(1178),"many times 1178 run")


54 many times 916 run
464 many times 936 run
625 many times 1178 run


**What are the age groups that were targeted through these ad campaigns?**

In [8]:
data_string=np.genfromtxt(data_file,delimiter=',',dtype='str',skip_header=1)
age=data_string[:,3]
print("Age groups targeted is given by ",age)


Age groups targeted is given by  ['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


**What was the average, minimum and maximum amount spent on the ads?**

In [9]:
#The average amount spent on the ads
spent=data[:,8]
avg_spent=np.average(spent)
print("The average amount spent on the ads is ",avg_spent)

The average amount spent on the ads is  51.36065613141295


In [10]:
#The max amount spent on the ads
spent=data[:,8]
max_spent=spent.max()
print("The MAX amount spent on the ads is ",max_spent)

The MAX amount spent on the ads is  639.9499981


In [11]:
#The min amount spent on the ads
spent=data[:,8]
min_spent=spent.min()
print("The MIN amount spent on the ads is ",min_spent)

The MIN amount spent on the ads is  0.0


**What is the id of the ad having the maximum number of clicks ?**

In [12]:
clicks=data[:,7]
a=clicks.max()
np.extract(a, ad_id[860])

array([1121814.])

**How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?**

In [13]:
aproved_conversion=data[861:,10]
a=len(aproved_conversion)
print(a,"have bought the product after seeing the ad with most clicks")
if max_spent == a :
  print("It is the max no.of purchases in this datasheet")
else:
  print("It is not the max no.of purchases in this datasheet")

282 have bought the product after seeing the ad with most clicks
It is not the max no.of purchases in this datasheet


**So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases**

In [14]:
print("Ad with the most clicks didn't fetch the maximum number of purchases")
purchases= data[: ,10]
max_purchases = purchases.max()
print( "product having maximum number of purchases",max_purchases)


Ad with the most clicks didn't fetch the maximum number of purchases
product having maximum number of purchases 21.0
