**Project-1**
Let us build a project to learn more about NumPy:

Features of the data set:

Age: Age of the person

education-num: No. of years of education they had

race: Person's race 0 - Amer-Indian-Eskimo
1 - Asian-Pac-Islander
2 - Black
3 - Other
4 - White

sex: Person's gender 0 - Female
1 - Male

capital-gain: Income from investment sources, apart from wages/salary

capital loss: Losses from investment sources, apart from wages/salary

hours-per-week: No. of hours per week the person works

income: Annual Income of the person
0 : Less than or equal to 50K
1 : More than 50K

**Step 1 : Import the Numpy Library & Read the data file.**

In [42]:
import numpy as np

In [43]:
data_file='/content/makeSenseOfCensus.csv'

**Step 2: Load the data.**

In [44]:
data=np.genfromtxt(data_file,delimiter=',',skip_header=1)

In [45]:
#print the data & type of data
print(data)
type(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


numpy.ndarray

**Step 3:Append the data.**
  **Append 'new_record' (given) to 'data' using "np.concatenate()".**   
        **new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]**

In [46]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
df=np.concatenate((data,new_record))
df

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

**Step 4 : Check if it's a young country or old country.**
          
    4.1 Create a new array called 'age' by taking only age column.
    (age is the column with index 0) of 'census' array.
    4.2 Find the max age and store it in a variable called 'max_age'.      
    4.3 Find the min age and store it in a variable called 'min_age'.
    4.4 Find the mean of the age and store it in a variable    
    called'age_mean'.
    4.5 Find the standard deviation of the age and store it in a            
    variable called 'age_std'




**4.1 Create a new array called 'age' by taking only age column(age is  
              the column with index 0) of 'census' array.**

In [47]:
#new Array age creation 
age=df[ : ,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [48]:
# find the length of age
len(age)

1001

**4.2 Find the max age and store it in a variable called 'max_age.**

In [49]:
max_age=age.max()

In [50]:
print("The max age is ",max_age)

The max age is  90.0


**4.3 Find the min age and store it in a variable called 'min_age'.**

In [51]:
min_age=age.min()
print("The Min age is ",min_age)

The Min age is  17.0


**4.4 Find the mean of the age and store it in a variable called 'age_mean'.**

In [52]:
age_mean=age.mean()
print("The mean of age is ",age_mean)

The mean of age is  38.06293706293706


**4.5 Find the standard deviation of the age and store it in a variable called 'age_std'**

In [53]:
age_std=np.std(age)
print("The standard deviation of the age is ",age_std)

The standard deviation of the age is  13.341478176165857


**Step 5: Let's check the country's race distribution to identify the minorities.**


**5.1 Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth).**



In [54]:
race=df[:,2]

In [55]:
race

array([4., 4., 4., ..., 4., 4., 4.])

In [56]:
race_0 = race[race == 0]
race_1 = race[race == 1]
race_2 = race[race == 2]
race_3 = race[race == 3]
race_4 = race[race == 4]

In [57]:
race_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
race_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
race_2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [60]:
race_3

array([3., 3., 3., 3., 3., 3.])

In [61]:
race_4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

**5.2 Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively.**

In [62]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

In [63]:
print("The length of race_0 is ",len_0)

The length of race_0 is  10


In [64]:
print("The length of race_1 is ",len_1)

The length of race_1 is  27


In [65]:
print("The length of race_2 is ",len_2)

The length of race_2 is  110


In [66]:
print("The length of race_3 is ",len_3)

The length of race_3 is  6


In [67]:
print("The length of race_4 is ",len_4)

The length of race_4 is  848


**5.3 Find out which is the race with the minimum no. of citizens.**

In [68]:
print('minimum no.of citizens',len_2,'present in the race 2')

minimum no.of citizens 110 present in the race 2


**5.4 store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens ).**

In [69]:
minority_race=len(race_3)
print("The race_3 is the minority_race =" ,minority_race," becz it is having least no.of citizens")

The race_3 is the minority_race = 6  becz it is having least no.of citizens


**Step 6: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place.**

**6.1 Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0).**

In [70]:
senior_citizen = age[age > 60]
senior_citizen

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

**6.2 Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'.**

In [71]:
working_hours = df[:,6]
working_hours

array([40., 13., 40., ..., 40., 50., 40.])

In [72]:
working_hours_sum = np.sum(working_hours[age > 60])
print("The total working hours of senior citizen is",working_hours_sum)

The total working hours of senior citizen is 1917.0


**6.3 Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'.**



In [73]:
senior_citizen_len=len(senior_citizen)
print("The length of senior_citizens is ",senior_citizen_len)

The length of senior_citizens is  61


**6.4 Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.**

In [74]:
avg_working_hours = working_hours_sum / senior_citizen_len
print("The Avg working hoursof senior_citizens is ",avg_working_hours)


The Avg working hoursof senior_citizens is  31.42622950819672


**6.5 Print 'avg_working_hours' and see if the govt. policy is followed.**

In [75]:
if avg_working_hours < 25:
  print('The govt policy is followed')
else:
  print('The govt policy is not followed')

The govt policy is not followed


**Step 7: Let's check that higher educated people have better pay in general.**

**7.1 Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.**

In [76]:
education = df[:,1]

In [77]:
education

array([13., 13.,  9., ..., 10., 13.,  9.])

In [78]:
income = df[:,7]
income

array([0., 0., 0., ..., 0., 1., 0.])

In [79]:
high = education[education > 10]
print("Higher education is ",high)
low = education[education <= 10]
print("Lower Education is ",low)

Higher education is  [13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 1

**7.2 Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.**

In [80]:
Avg_pay_high = np.mean(high)
print("The avg pay high is ",Avg_pay_high)

The avg pay high is  12.954128440366972


In [81]:
Avg_pay_low = np.mean(low)
print("The avg pay Low is ",Avg_pay_low)

The avg pay Low is  8.689910979228486
